import copy
from datetime import datetime, timezone

from PySide6.QtCore import QPointF

from merisor.application import (
    DiagramController,
    McdToMldTransformer,
    SQLGenerator,
    SQLTarget,
)
from merisor.domain import (
    Attribute,
    MCDModel,
    MLDDataType,
    MLDDataTypeName,
    Position,
    validate_mcd,
)
from merisor.persistence import JsonDiagramRepository
from merisor.ui.canvas import DiagramScene
from merisor.ui.main_window import MainWindow


def _complete_client_model() -> tuple[MCDModel, str, str, str]:
    model = MCDModel()
    client = model.create_entity("CLIENT", Position())
    identifier = model.create_attribute(
        client.id,
        "id_client",
        identifier=True,
        data_type=MLDDataType(MLDDataTypeName.BIGINT),
        nullable=False,
        auto_increment=True,
        comment="Identifiant technique",
    )
    email = model.create_attribute(
        client.id,
        "email",
        data_type=MLDDataType.varchar(255),
        nullable=False,
        default="'inconnu@example.test'",
        unique=True,
        comment="Adresse électronique principale",
        constraints=("email <> ''",),
    )
    active = model.create_attribute(
        client.id,
        "actif",
        data_type=MLDDataType(MLDDataTypeName.BOOLEAN),
        nullable=False,
        default="TRUE",
    )
    return model, identifier.id, email.id, active.id


def test_complete_attribute_defaults_are_backward_compatible() -> None:
    attribute = Attribute("nom")

    assert attribute.data_type is None
    assert attribute.nullable is None
    assert attribute.default is None
    assert attribute.unique is False
    assert attribute.comment == ""
    assert attribute.auto_increment is False
    assert attribute.constraints == ()


def test_complete_attribute_json_round_trip_and_old_json_defaults() -> None:
    model, _, email_id, _ = _complete_client_model()
    repository = JsonDiagramRepository()
    payload = repository.to_dict(model)
    loaded = repository.from_dict(payload)
    email = next(
        attribute
        for entity in loaded.entities.values()
        for attribute in entity.attributes
        if attribute.id == email_id
    )

    assert email.data_type == MLDDataType.varchar(255)
    assert email.nullable is False
    assert email.default == "'inconnu@example.test'"
    assert email.unique
    assert email.comment == "Adresse électronique principale"
    assert email.constraints == ("email <> ''",)

    old_payload = copy.deepcopy(payload)
    for raw_attribute in old_payload["entities"][0]["attributes"]:
        for key in (
            "nullable",
            "default",
            "unique",
            "comment",
            "auto_increment",
            "constraints",
        ):
            raw_attribute.pop(key)
    old_loaded = repository.from_dict(old_payload)
    old_email = old_loaded.attribute(next(iter(old_loaded.entities)), email_id)
    assert old_email.nullable is None
    assert old_email.default is None
    assert not old_email.unique
    assert old_email.comment == ""
    assert not old_email.auto_increment
    assert old_email.constraints == ()


def test_complete_attributes_reach_mld_and_all_sql_dialects() -> None:
    model, identifier_id, email_id, active_id = _complete_client_model()
    mld = McdToMldTransformer().transform(model)
    table = mld.tables[0]
    columns = {column.source_attribute_id: column for column in table.columns}

    assert columns[identifier_id].auto_increment
    assert columns[identifier_id].comment == "Identifiant technique"
    assert columns[email_id].nullable is False
    assert columns[email_id].default == "'inconnu@example.test'"
    assert columns[email_id].comment == "Adresse électronique principale"
    assert columns[active_id].default == "TRUE"
    assert table.is_unique(columns[email_id].id)
    assert [check.expression for check in table.check_constraints] == ["email <> ''"]

    generator = SQLGenerator()
    generated_at = datetime(2026, 8, 31, tzinfo=timezone.utc)
    postgres = generator.generate(mld, SQLTarget.POSTGRESQL, generated_at=generated_at)
    sqlite = generator.generate(mld, SQLTarget.SQLITE, generated_at=generated_at)
    mysql = generator.generate(mld, SQLTarget.MYSQL, generated_at=generated_at)

    assert "GENERATED BY DEFAULT AS IDENTITY" in postgres
    assert "DEFAULT TRUE" in postgres
    assert 'UNIQUE ("email")' in postgres
    assert "CHECK (email <> '')" in postgres
    assert 'COMMENT ON COLUMN "CLIENT"."email"' in postgres
    assert "PRIMARY KEY AUTOINCREMENT" in sqlite
    assert "-- Commentaire CLIENT.email" in sqlite
    assert "AUTO_INCREMENT" in mysql
    assert "COMMENT 'Adresse électronique principale'" in mysql


def test_complete_attribute_editor_is_undoable(qapp) -> None:  # type: ignore[no-untyped-def]
    window = MainWindow()
    entity = window.controller.create_entity("CLIENT", QPointF())
    attribute = window.controller.add_attribute(entity.id, "courriel")
    window.controller._node_items[entity.id].setSelected(True)
    qapp.processEvents()
    panel = window.properties_panel
    item = panel.attribute_tree.topLevelItem(0)
    assert item is not None
    panel.attribute_tree.setCurrentItem(item)

    panel.attribute_name_edit.setText("email")
    panel.attribute_type_combo.setCurrentIndex(
        panel.attribute_type_combo.findData(MLDDataTypeName.VARCHAR.value)
    )
    panel.attribute_length.setValue(255)
    panel.attribute_nullable_combo.setCurrentIndex(1)
    panel.attribute_default_edit.setText("'contact@example.test'")
    panel.attribute_unique_checkbox.setChecked(True)
    panel.attribute_comment_edit.setPlainText("Courriel de connexion")
    panel.attribute_constraints_edit.setPlainText("email <> ''\nlength(email) >= 3")
    panel.apply_attribute_type_button.click()

    assert attribute.name == "email"
    assert attribute.data_type == MLDDataType.varchar(255)
    assert attribute.nullable is False
    assert attribute.default == "'contact@example.test'"
    assert attribute.unique
    assert attribute.comment == "Courriel de connexion"
    assert attribute.constraints == ("email <> ''", "length(email) >= 3")
    refreshed_item = panel.attribute_tree.topLevelItem(0)
    assert refreshed_item is not None
    assert refreshed_item.text(3) == "NOT NULL"
    assert refreshed_item.text(4) == "Oui"

    window.controller.undo_stack.undo()
    assert attribute.name == "courriel"
    assert attribute.data_type is None
    assert attribute.nullable is None
    assert attribute.default is None
    assert not attribute.unique
    assert attribute.comment == ""
    assert attribute.constraints == ()
    window.controller.undo_stack.setClean()
    window.close()


def test_auto_increment_validation_is_explained() -> None:
    model = MCDModel()
    entity = model.create_entity("CLIENT", Position())
    model.create_attribute(entity.id, "id_client", identifier=True)
    model.create_attribute(
        entity.id,
        "code",
        data_type=MLDDataType(MLDDataTypeName.TEXT),
        auto_increment=True,
    )

    codes = {issue.code for issue in validate_mcd(model).errors}

    assert "attribute.auto_increment_not_identifier" in codes
    assert "attribute.auto_increment_type" in codes


def test_controller_can_apply_all_attribute_properties_directly(qapp) -> None:  # type: ignore[no-untyped-def]
    controller = DiagramController(DiagramScene())
    entity = controller.create_entity("PRODUIT", QPointF())
    attribute = controller.add_attribute(entity.id, "prix")

    controller.update_attribute(
        entity.id,
        attribute.id,
        name="prix_ttc",
        data_type=MLDDataType(MLDDataTypeName.DECIMAL, precision=10, scale=2),
        nullable=False,
        default="0",
        unique=False,
        comment="Prix toutes taxes comprises",
        identifier=False,
        auto_increment=False,
        constraints=("prix_ttc >= 0",),
    )

    assert attribute.name == "prix_ttc"
    assert attribute.nullable is False
    assert attribute.constraints == ("prix_ttc >= 0",)
    controller.undo_stack.undo()
    assert attribute.name == "prix"
    assert attribute.nullable is None
