"""Objets métier indépendants de l'interface graphique."""

from merisor.domain.model import (
    Association,
    Attribute,
    Cardinality,
    CardinalityMaximum,
    CardinalityMinimum,
    DEFAULT_CARDINALITY,
    DiagramError,
    DiagramModel,
    Entity,
    MCDModel,
    MaterializationStrategy,
    Position,
    Relation,
)
from merisor.domain.mld import (
    MLDCheckConstraint,
    MLDColumn,
    MLDDataType,
    MLDDataTypeName,
    MLDError,
    MLDForeignKey,
    MLDIndex,
    MLDModel,
    MLDReferentialAction,
    MLDTable,
    MLDTableSource,
    MLDUniqueConstraint,
)
from merisor.domain.validation import (
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    validate_mcd,
)

__all__ = [
    "Association",
    "Attribute",
    "Cardinality",
    "CardinalityMaximum",
    "CardinalityMinimum",
    "DEFAULT_CARDINALITY",
    "DiagramError",
    "DiagramModel",
    "Entity",
    "MCDModel",
    "MaterializationStrategy",
    "MLDCheckConstraint",
    "MLDColumn",
    "MLDDataType",
    "MLDDataTypeName",
    "MLDError",
    "MLDForeignKey",
    "MLDIndex",
    "MLDModel",
    "MLDReferentialAction",
    "MLDTable",
    "MLDTableSource",
    "MLDUniqueConstraint",
    "Position",
    "Relation",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "validate_mcd",
]
