"""Logique applicative et coordination modèle-interface."""

from merisor.application.ai_mcd_service import (
    AiMcdCandidate,
    AiMcdService,
    AiMcdValidationError,
)
from merisor.application.ai_normalization_service import (
    AiDependencySuggestion,
    AiNormalizationError,
    AiNormalizationService,
)
from merisor.application.ai_repair_service import (
    AiRepairError,
    AiRepairProposal,
    AiRepairReport,
    AiRepairService,
    RepairConfidence,
)
from merisor.application.business_scenarios import (
    BusinessScenario,
    BusinessScenarioAnalyzer,
    BusinessScenarioReport,
    ScenarioCheck,
    ScenarioCheckStatus,
    ScenarioPathElement,
    parse_scenario,
)
from merisor.application.controller import DiagramController, MLDGenerationBlocked
from merisor.application.conversational_design_service import (
    CONVERSATIONAL_SYSTEM_PROMPT,
    ConversationalDesignService,
)
from merisor.application.data_dictionary import (
    DataDictionary,
    DataDictionaryEntry,
    DataDictionaryService,
    DictionaryEntryKind,
)
from merisor.application.ddl_importer import (
    DDLImportError,
    DDLImportResult,
    SQLDDLImporter,
)
from merisor.application.design_session import (
    DESIGN_STAGES,
    ConceptKind,
    DesignAssistantResponse,
    DesignJustification,
    DesignQuestion,
    DesignSession,
    DesignSessionError,
    DesignStage,
    DesignStep,
    DetectedConcept,
    DraftPatch,
    DraftPatchApplier,
    DraftRevision,
    ModelDifference,
    compare_models,
)
from merisor.application.diagram_text_exporter import (
    DiagramTextExporter,
    DiagramTextExportError,
    DiagramTextFormat,
)
from merisor.application.documentation_catalog import (
    DOCUMENTATION_PAGES,
    DocumentationCatalog,
    DocumentationError,
    DocumentationPage,
)
from merisor.application.documentation_generator import (
    ModelDocumentation,
    ModelDocumentationGenerator,
)
from merisor.application.impact_analysis import (
    ImpactCertainty,
    ImpactReference,
    ImpactReport,
    ImpactTarget,
    ModelImpactAnalyzer,
)
from merisor.application.mcd_layout import McdAutoLayout
from merisor.application.mld_text import render_mld_text
from merisor.application.mld_transformer import (
    McdToMldTransformer,
    MLDNamePolicy,
    MLDTransformationError,
    mcd_logical_fingerprint,
)
from merisor.application.model_explorer import (
    ExplorationOptions,
    ExplorationResult,
    ExplorationSearchResult,
    ModelExplorer,
)
from merisor.application.openrouter_client import (
    OpenRouterClient,
    OpenRouterError,
    OpenRouterModel,
)
from merisor.application.openrouter_settings import OpenRouterKeyStore
from merisor.application.pwa_source_importer import (
    InferenceConfidence,
    PwaImportError,
    PwaImportResult,
    PwaSourceImporter,
    SourceEvidence,
)
from merisor.application.query_generator import (
    QueryGenerationError,
    QueryGenerationResult,
    QueryTarget,
    SQLQueryGenerator,
)
from merisor.application.sql_generator import (
    MLDSQLValidator,
    MySQLDialect,
    PostgreSQLDialect,
    SQLDialect,
    SQLGenerationError,
    SQLGenerationOptions,
    SQLGenerator,
    SQLiteDialect,
    SQLTarget,
    SQLValidationIssue,
    SQLValidationReport,
    SQLValidationSeverity,
    sql_dialect,
)
from merisor.application.student_mode import (
    COMMAND_ORDER_EXERCISE,
    STUDENT_EXERCISES,
    AssociationExpectation,
    CardinalityExpectation,
    StudentCriterion,
    StudentCriterionStatus,
    StudentExercise,
    StudentExerciseEvaluator,
    StudentExerciseReport,
)
from merisor.application.submodels import (
    GLOBAL_SCOPE_ID,
    SubmodelResolver,
    SubmodelScope,
)
from merisor.application.test_data_generator import (
    TestDataGenerationError,
    TestDataGenerationResult,
    TestDataGenerator,
    TestDataIssue,
)
from merisor.application.traceability import (
    ModelTraceabilityService,
    TraceabilityReport,
)
from merisor.application.transformation_explainer import (
    MldTransformationExplainer,
    TransformationExplanation,
    TransformationExplanationReport,
)
from merisor.application.version_comparator import (
    ChangeImpact,
    ChangeKind,
    ModelVersionComparator,
    VersionChange,
    VersionComparison,
)
from merisor.application.what_if_analysis import (
    ImpactLayer,
    WhatIfAnalyzer,
    WhatIfImpact,
    WhatIfOperation,
    WhatIfReport,
)

__all__ = [
    "COMMAND_ORDER_EXERCISE",
    "CONVERSATIONAL_SYSTEM_PROMPT",
    "DESIGN_STAGES",
    "DOCUMENTATION_PAGES",
    "GLOBAL_SCOPE_ID",
    "STUDENT_EXERCISES",
    "AiDependencySuggestion",
    "AiMcdCandidate",
    "AiMcdService",
    "AiMcdValidationError",
    "AiNormalizationError",
    "AiNormalizationService",
    "AiRepairError",
    "AiRepairProposal",
    "AiRepairReport",
    "AiRepairService",
    "AssociationExpectation",
    "BusinessScenario",
    "BusinessScenarioAnalyzer",
    "BusinessScenarioReport",
    "CardinalityExpectation",
    "ChangeImpact",
    "ChangeKind",
    "ConceptKind",
    "ConversationalDesignService",
    "DDLImportError",
    "DDLImportResult",
    "DataDictionary",
    "DataDictionaryEntry",
    "DataDictionaryService",
    "DesignAssistantResponse",
    "DesignJustification",
    "DesignQuestion",
    "DesignSession",
    "DesignSessionError",
    "DesignStage",
    "DesignStep",
    "DetectedConcept",
    "DiagramController",
    "DiagramTextExportError",
    "DiagramTextExporter",
    "DiagramTextFormat",
    "DictionaryEntryKind",
    "DocumentationCatalog",
    "DocumentationError",
    "DocumentationPage",
    "DraftPatch",
    "DraftPatchApplier",
    "DraftRevision",
    "ExplorationOptions",
    "ExplorationResult",
    "ExplorationSearchResult",
    "ImpactCertainty",
    "ImpactLayer",
    "ImpactReference",
    "ImpactReport",
    "ImpactTarget",
    "InferenceConfidence",
    "MLDGenerationBlocked",
    "MLDNamePolicy",
    "MLDSQLValidator",
    "MLDTransformationError",
    "McdAutoLayout",
    "McdToMldTransformer",
    "MldTransformationExplainer",
    "ModelDifference",
    "ModelDocumentation",
    "ModelDocumentationGenerator",
    "ModelExplorer",
    "ModelImpactAnalyzer",
    "ModelTraceabilityService",
    "ModelVersionComparator",
    "MySQLDialect",
    "OpenRouterClient",
    "OpenRouterError",
    "OpenRouterKeyStore",
    "OpenRouterModel",
    "PostgreSQLDialect",
    "PwaImportError",
    "PwaImportResult",
    "PwaSourceImporter",
    "QueryGenerationError",
    "QueryGenerationResult",
    "QueryTarget",
    "RepairConfidence",
    "SQLDDLImporter",
    "SQLDialect",
    "SQLGenerationError",
    "SQLGenerationOptions",
    "SQLGenerator",
    "SQLQueryGenerator",
    "SQLTarget",
    "SQLValidationIssue",
    "SQLValidationReport",
    "SQLValidationSeverity",
    "SQLiteDialect",
    "ScenarioCheck",
    "ScenarioCheckStatus",
    "ScenarioPathElement",
    "SourceEvidence",
    "StudentCriterion",
    "StudentCriterionStatus",
    "StudentExercise",
    "StudentExerciseEvaluator",
    "StudentExerciseReport",
    "SubmodelResolver",
    "SubmodelScope",
    "TestDataGenerationError",
    "TestDataGenerationResult",
    "TestDataGenerator",
    "TestDataIssue",
    "TraceabilityReport",
    "TransformationExplanation",
    "TransformationExplanationReport",
    "VersionChange",
    "VersionComparison",
    "WhatIfAnalyzer",
    "WhatIfImpact",
    "WhatIfOperation",
    "WhatIfReport",
    "compare_models",
    "mcd_logical_fingerprint",
    "parse_scenario",
    "render_mld_text",
    "sql_dialect",
]
